
authentication:
    oauth:
        clientid: clientapp
        secret: 123456
        # Token is valid 30 minutes
        tokenValidityInSeconds: 7200

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl_auto: none
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
            default_schema: public

# use wisely!
flyway:
    locations: classpath:db/migration
    schemas: public
#    validateOnMigrate: false

swagger:
    title: Bandit Spring Angular
    description: REST API, which powers the single page web app and others
    version: 0.0.1
    termsOfServiceUrl: ''
    contact: Maav
    license: The MIT License (MIT)
    licenseUrl:  ''
